package com.mycompany.ejemplo04.domain;

import static com.mycompany.ejemplo04.domain.AssertUtils.bigDecimalCompareTo;
import static com.mycompany.ejemplo04.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class TablaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaAllPropertiesEquals(Tabla expected, Tabla actual) {
        assertTablaAutoGeneratedPropertiesEquals(expected, actual);
        assertTablaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaAllUpdatablePropertiesEquals(Tabla expected, Tabla actual) {
        assertTablaUpdatableFieldsEquals(expected, actual);
        assertTablaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaAutoGeneratedPropertiesEquals(Tabla expected, Tabla actual) {
        assertThat(actual)
            .as("Verify Tabla auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaUpdatableFieldsEquals(Tabla expected, Tabla actual) {
        assertThat(actual)
            .as("Verify Tabla relevant properties")
            .satisfies(a -> assertThat(a.getCampo01()).as("check campo01").isEqualTo(expected.getCampo01()))
            .satisfies(a -> assertThat(a.getCampo02()).as("check campo02").isEqualTo(expected.getCampo02()))
            .satisfies(a -> assertThat(a.getCampo03()).as("check campo03").isEqualTo(expected.getCampo03()))
            .satisfies(a ->
                assertThat(a.getCampo04()).as("check campo04").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCampo04())
            )
            .satisfies(a -> assertThat(a.getCampo05()).as("check campo05").isEqualTo(expected.getCampo05()))
            .satisfies(a -> assertThat(a.getCampo06()).as("check campo06").isEqualTo(expected.getCampo06()))
            .satisfies(a -> assertThat(a.getCampo07()).as("check campo07").isEqualTo(expected.getCampo07()))
            .satisfies(a -> assertThat(a.getCampo08()).as("check campo08").isEqualTo(expected.getCampo08()))
            .satisfies(a ->
                assertThat(a.getCampo09()).as("check campo09").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getCampo09())
            )
            .satisfies(a -> assertThat(a.getCampo10()).as("check campo10").isEqualTo(expected.getCampo10()))
            .satisfies(a -> assertThat(a.getCampo11()).as("check campo11").isEqualTo(expected.getCampo11()))
            .satisfies(a -> assertThat(a.getCampo12()).as("check campo12").isEqualTo(expected.getCampo12()))
            .satisfies(a -> assertThat(a.getCampo13()).as("check campo13").isEqualTo(expected.getCampo13()))
            .satisfies(a -> assertThat(a.getCampo14()).as("check campo14").isEqualTo(expected.getCampo14()))
            .satisfies(a ->
                assertThat(a.getCampo14ContentType()).as("check campo14 content type").isEqualTo(expected.getCampo14ContentType())
            )
            .satisfies(a -> assertThat(a.getCampo15()).as("check campo15").isEqualTo(expected.getCampo15()))
            .satisfies(a ->
                assertThat(a.getCampo15ContentType()).as("check campo15 content type").isEqualTo(expected.getCampo15ContentType())
            )
            .satisfies(a -> assertThat(a.getCampo16()).as("check campo16").isEqualTo(expected.getCampo16()))
            .satisfies(a ->
                assertThat(a.getCampo16ContentType()).as("check campo16 content type").isEqualTo(expected.getCampo16ContentType())
            )
            .satisfies(a -> assertThat(a.getCampo17()).as("check campo17").isEqualTo(expected.getCampo17()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTablaUpdatableRelationshipsEquals(Tabla expected, Tabla actual) {
        // empty method
    }
}
