/**
 * This package file was generated by JHipster
 */
<<<<<<< Updated upstream:jhipster/ejercicio220/src/main/java/com/mycompany/ejemplo04/service/impl/package-info.java
package com.mycompany.ejemplo04.service.impl;
=======
package com.mycompany.ejemplo03.service.impl;
>>>>>>> Stashed changes:jhipster/ejemplo03/src/main/java/com/mycompany/ejemplo03/service/impl/package-info.java
