# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGE3YWY5NmU5M2FiMTA3ZDE2Zjc0NmQyZGJhNTY3OGRhMTA1NDk2YjcwZmQyZmM0YWRkNzY5MzkwNzE2YTUzZjk0ODUwNjg4NDQ2OWExMTIyNDg3YmVhZmJlY2MwNjNmMjJhM2E3NmQ1ZjZkNzRlNWYzOWRhM2E4NzcwNzczMzY=
